### ISSUE TITLE
Updating node

### ISSUE THREAD

**Issue by dlomax64** [ssc-oscar/DRE#63]
@audrism I'm almost done updating the website, but some of the new versions of packages require node >= 12.13.0. We are currently using version 10.20.1. Would it be possible for you to update it? I tried but I don't have the permissions to.

**Comment by audrism** [comment]
Will do later today

**Comment by dlomax64** [comment]
Just to add to this, you might want to update to either version Node 14 or 16. Version 10 reached the end of active support a year ago and reached the end of security support 2 months ago. 12 leaves security support in 10 months and is already out of active support.

![image](https://user-images.githubusercontent.com/53716031/124284825-531de480-db1b-11eb-9e36-a6b088495f7a.png)

**Comment by audrism** [comment]
Thank you! 

Does npm install do the updates or do I need to update ubuntu npm package first?

**Comment by dlomax64** [comment]
If you are talking about updating node, here's what I found: 
![image](https://user-images.githubusercontent.com/53716031/124287688-4ea6fb00-db1e-11eb-8937-de5b4869a61d.png)

If you are talking about the packages that I updated: 
I will make a PR that will include an updated package.json that will tell npm which version of each package to update to. So once you pull that `npm update` should be all you need to do

**Comment by audrism** [comment]
I have installed n, upgraded npm but 
```
sudo npm install -g
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/MERN-boilerplate/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/MERN-boilerplate/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ MERN-boilerplate@1.0.0
```

finally: 
```
sudo npm run start:dev

> MERN-boilerplate@1.0.0 start:dev /home/audris/swsc/DRE
> PORT=3000 node server

internal/modules/cjs/loader.js:1144
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/home/audris/swsc/DRE/node_modules/bcrypt/lib/binding/bcrypt_lib.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
```

**Comment by dlomax64** [comment]
I've been getting those warnings about fsevents too. Node is still showing up as version 10.20.1 in my container. For the bcrypt error try: `npm rebuild bcrypt`

**Comment by audrism** [comment]
```
npm -v 
7.19.1

node -v 
v14.17.2

```
but 
```
npm run start:dev

Require stack:
- /home/audris/swsc/DRE1/node_modules/bcrypt/bcrypt.js
- /home/audris/swsc/DRE1/server/models/User.js
- /home/audris/swsc/DRE1/server/routes/api/sampling.js
- /home/audris/swsc/DRE1/server/routes/index.js
- /home/audris/swsc/DRE1/server/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/audris/swsc/DRE1/node_modules/bcrypt/bcrypt.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/audris/swsc/DRE1/server/models/User.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/audris/swsc/DRE1/server/routes/api/sampling.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/audris/swsc/DRE1/node_modules/bcrypt/bcrypt.js',
    '/home/audris/swsc/DRE1/server/models/User.js',
    '/home/audris/swsc/DRE1/server/routes/api/sampling.js',
    '/home/audris/swsc/DRE1/server/routes/index.js',
    '/home/audris/swsc/DRE1/server/server.js'
  ]
}
```

**Comment by dlomax64** [comment]
![image](https://user-images.githubusercontent.com/53716031/124356267-174e5200-dbe3-11eb-8989-85fc14b3b339.png)

Is there something I need to do in my container to get the new versions?

**Comment by audrism** [comment]
Ok, now I realized what you mean: mern docker, right?

**Comment by dlomax64** [comment]
Yes. How do I pull new docker image?

**Comment by dlomax64** [comment]
Is this the command I need to do with the new dockerfile? `docker build {name} .`

**Comment by audrism** [comment]
Docker build  .

**Comment by dlomax64** [comment]
Alright, I figured it out and now am running on the new versions! I'll work on getting everything working and submit a PR asap
